package Frames;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kyriakos
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    
    static String     driverClassName = "org.postgresql.Driver" ;
    static String     url             = "jdbc:postgresql://dblabs.it.teithe.gr:5432/it144353" ;
    static String     username = "it144353";
    static String     passwd = "Cc_17051996";
    static Connection dbConnection    = null;
    static Statement  statement       = null;
    static ResultSet rsSearchForIdentifiedUser= null;
    private PreparedStatement pst = null;
    
    public LogIn() throws Exception {
        initComponents();
        init();
        Class.forName (driverClassName);
        dbConnection = DriverManager.getConnection (url, username, passwd);
        statement    = dbConnection.createStatement();
        
    }
    
    
    
    
    
    public void close() {

        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);

    }
    
    private void init() {
        setTitle("Log In Window");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        studentIDTextField = new javax.swing.JTextField();
        login_button = new javax.swing.JButton();
        EpistrofhButton = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LogIn");
        setBackground(new java.awt.Color(255, 255, 153));
        setMaximumSize(new java.awt.Dimension(400, 400));
        setPreferredSize(new java.awt.Dimension(400, 400));

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("ΦΟΡΜΑ ΣΥΝΔΕΣΗΣ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 230, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Student ID:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 120, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("PASSWORD:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 120, -1));

        studentIDTextField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(studentIDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 180, 25));

        login_button.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        login_button.setText("ΕΙΣΟΔΟΣ");
        login_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(login_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 140, 50));

        EpistrofhButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        EpistrofhButton.setText("ΕΠΙΣΤΡΟΦΗ");
        EpistrofhButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EpistrofhButtonActionPerformed(evt);
            }
        });
        jPanel1.add(EpistrofhButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, 50));
        jPanel1.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 180, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EpistrofhButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EpistrofhButtonActionPerformed
        // TODO add your handling code here:
        new HomeMenu().setVisible(true);
           this.hide();
    }//GEN-LAST:event_EpistrofhButtonActionPerformed

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        String studentID =  studentIDTextField.getText();
        String password = passwordField.getText();
        
        
        String SearchForIdentifiedUser 
                = " SELECT onomaMathiti FROM B2 WHERE StudentID = ? AND passwd = ? " ;
        
             
        try {
            
            pst = dbConnection.prepareStatement(SearchForIdentifiedUser);
            pst.setString(1, studentID);
            pst.setString(2, password);
            
            rsSearchForIdentifiedUser = pst.executeQuery();
 
             
            if("999999".equals(studentID) && "99996666".equals(password)){
                //αν συνδεθει ΜΟΝΟ ο διευθυντης θα μπορει να δει τα αποτελεσματα των μαθητων του τμηματος
                
                JOptionPane.showMessageDialog(rootPane, " Log in succesful!  \n Καλωσήρθατε κύριε διευθυντά ");
                this.dispose();
                CheckResults object = new CheckResults();
                object.setVisible(true);
                
                }
            else {
             
            if (rsSearchForIdentifiedUser.next()) {
                

                
                JOptionPane.showMessageDialog(rootPane, "  Log in succesful!  \n  Παρακαλώ συμπληρώστε το Quiz! ");
                this.hide();
                PsychologyQuiz obj = new PsychologyQuiz(studentID);
                obj.setVisible(true);
                try {
                    rsSearchForIdentifiedUser.close();
                    pst.close();
                    dbConnection.close();    
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, e);
                }
                
            }
            else{     
                JOptionPane.showMessageDialog(rootPane, "Student ID and Password are not correct... \n Please try again!" );  
            } }
        
        } catch(SQLException ex) {
            System.out.println("\n -- SQL Exception --- \n");
            while(ex != null) {
                    System.out.println("Message: " + ex.getMessage());
                    System.out.println("SQLState: " + ex.getSQLState());
                    System.out.println("ErrorCode: " + ex.getErrorCode());
                    ex = ex.getNextException();
                    System.out.println("");
	}
     }  catch (Exception ex) {
            Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
        }
     
     
        
            
    }//GEN-LAST:event_login_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        
 
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run()  {
                try {
                    new LogIn().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EpistrofhButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login_button;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField studentIDTextField;
    // End of variables declaration//GEN-END:variables
}
