package Frames;


import java.awt.Container;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author choul
 */
public class PsychologyQuiz extends javax.swing.JFrame {

    /**
     * Creates new form PsychologyQuiz
     */
    
    static String     driverClassName = "org.postgresql.Driver" ;
    static String     url             = "jdbc:postgresql://dblabs.it.teithe.gr:5432/it144353" ;
    static String     username = "it144353";
    static String     passwd = "Cc_17051996";
    static Connection dbConnection    = null;
    static Statement  statement       = null;
    static ResultSet rs = null;
    private PreparedStatement pst = null;
    
    
    public PsychologyQuiz() throws Exception {
        initComponents();
        init();
        
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        Container c = getContentPane();
        JScrollPane scroll = new JScrollPane( c );
        setContentPane( scroll ); 
        
            
        
        Class.forName (driverClassName);
        dbConnection = DriverManager.getConnection (url, username, passwd);
        statement    = dbConnection.createStatement();
    }
    
    public PsychologyQuiz(String StudentIdParam) throws Exception {
        initComponents();
        init();
        this.labelStudentId.setText(StudentIdParam);

        setExtendedState(JFrame.MAXIMIZED_BOTH);
        Container c = getContentPane();
        JScrollPane scroll = new JScrollPane( c );
        setContentPane( scroll ); 
        
        Class.forName (driverClassName);
        dbConnection = DriverManager.getConnection (url, username, passwd);
        statement    = dbConnection.createStatement();
        }

    private void init() {
        setTitle("Quiz Window");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setResizable(false);
    }
    
    public void close() {

        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelStudentId = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Q11 = new javax.swing.JRadioButton();
        Q13 = new javax.swing.JRadioButton();
        Q12 = new javax.swing.JRadioButton();
        Q14 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        Q21 = new javax.swing.JRadioButton();
        Q22 = new javax.swing.JRadioButton();
        Q23 = new javax.swing.JRadioButton();
        Q24 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        Q31 = new javax.swing.JRadioButton();
        Q33 = new javax.swing.JRadioButton();
        Q32 = new javax.swing.JRadioButton();
        Q34 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        Q41 = new javax.swing.JRadioButton();
        Q43 = new javax.swing.JRadioButton();
        Q42 = new javax.swing.JRadioButton();
        Q44 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        Q51 = new javax.swing.JRadioButton();
        Q52 = new javax.swing.JRadioButton();
        Q53 = new javax.swing.JRadioButton();
        Q54 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        Q81 = new javax.swing.JRadioButton();
        Q83 = new javax.swing.JRadioButton();
        Q82 = new javax.swing.JRadioButton();
        Q84 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Q71 = new javax.swing.JRadioButton();
        Q72 = new javax.swing.JRadioButton();
        Q73 = new javax.swing.JRadioButton();
        Q74 = new javax.swing.JRadioButton();
        Q61 = new javax.swing.JRadioButton();
        Q62 = new javax.swing.JRadioButton();
        Q63 = new javax.swing.JRadioButton();
        Q64 = new javax.swing.JRadioButton();
        Q91 = new javax.swing.JRadioButton();
        Q92 = new javax.swing.JRadioButton();
        Q93 = new javax.swing.JRadioButton();
        Q94 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        Q101 = new javax.swing.JRadioButton();
        Q103 = new javax.swing.JRadioButton();
        Q102 = new javax.swing.JRadioButton();
        Q104 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        calc_button = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("ΑΠΑΝΤΗΣΤΕ ΣΤΙΣ ΠΑΡΑΚΑΤΩ ΕΡΩΤΗΣΕΙΣ (ΜΙΑ ΑΠΑΝΤΗΣΗ ΓΙΑ ΚΑΘΕ ΕΡΩΤΗΣΗ)");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("User's StudentID: ");

        labelStudentId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("1.Με πόση άνεση εκφέρεις την αποψή σου στο μάθημα?");

        buttonGroup1.add(Q11);
        Q11.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Q11.setText("Α. Με μεγάλη άνεση");

        buttonGroup1.add(Q13);
        Q13.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Q13.setText("Γ.  Άνετα αλλά με ενδοιασμό");

        buttonGroup1.add(Q12);
        Q12.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Q12.setText("Β. Δεν εκφέρω ποτέ άποψη");

        buttonGroup1.add(Q14);
        Q14.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Q14.setText("<html> Δ. Δε νιώθω άνετα\n<br> (όταν συμμετέχω) <html>");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("2.Πως αισθάνεσαι την περίοδο των εξετάσεων?");

        buttonGroup2.add(Q21);
        Q21.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Q21.setText("Α. Έχω μέτριας έντασης άγχος");

        buttonGroup2.add(Q22);
        Q22.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Q22.setText("Β. Δεν αισθάνομαι κάτι");

        buttonGroup2.add(Q23);
        Q23.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Q23.setText("Γ. Αρκετά καλά");

        buttonGroup2.add(Q24);
        Q24.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Q24.setText("<html> Δ. Υποφέρω απο άγχος/ <br> κρίσεις πανικού </html>");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("<html> 3.Πόσο απαιτητικοί είναι οι γονείς σου <br> με τις σχολικές σου επιδόσεις? </html>");

        buttonGroup3.add(Q31);
        Q31.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Q31.setText("Α. Δεν ενδιαφέρονται για μένα");

        buttonGroup3.add(Q33);
        Q33.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Q33.setText("<html> Γ. Δεν με πιέζουν θέλουν \n<br> όμως να έχω καλές επιδόσεις <html>");

        buttonGroup3.add(Q32);
        Q32.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Q32.setText("<html> Β. Καθόλου απαιτητικοί \n<br> (Με στηρίζουν) </html>");

        buttonGroup3.add(Q34);
        Q34.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Q34.setText("Δ. Είναι πολύ απαιτητικοί");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("4.Πως είναι η σχέση σου με τους γονείς σου?");

        buttonGroup4.add(Q41);
        Q41.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Q41.setText("Α. Μέτρια");

        buttonGroup4.add(Q43);
        Q43.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Q43.setText("Γ. Καθόλου καλή");

        buttonGroup4.add(Q42);
        Q42.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Q42.setText("Β. Πολύ καλή");

        buttonGroup4.add(Q44);
        Q44.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Q44.setText("Δ. Καλή");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("5.Υποφέρεις από κρίσεις πανικού?");

        buttonGroup5.add(Q51);
        Q51.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Q51.setText("Α. Σπάνια");

        buttonGroup5.add(Q52);
        Q52.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Q52.setText("<html> Β. Ναι, όμως  <br> το διαχειρίζομαι </html>");

        buttonGroup5.add(Q53);
        Q53.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Q53.setText("Γ. Όχι");

        buttonGroup5.add(Q54);
        Q54.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Q54.setText("<html> Δ. Ναι, σε μη <br> διαχειρίσιμο βαθμό </html>");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("6.Πως διαχειρίζεσαι το άγχος?");

        buttonGroup8.add(Q81);
        Q81.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Q81.setText("Α. Προσπαθώ να ηρεμήσω");

        buttonGroup8.add(Q83);
        Q83.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Q83.setText("<html> Γ. Καταστρέφω πράγματα , <br> χτυπάω τους άλλους </html>");

        buttonGroup8.add(Q82);
        Q82.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Q82.setText("<html> Β. Φωνάζω,βρίζω, <br> διαπληκτίζομαι με άλλους </html>");

        buttonGroup8.add(Q84);
        Q84.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Q84.setText("Δ. Δεν δίνω σημασία");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText("7.Πως αντιδράς σε μια απόρριψη?");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setText("8.Πως αντιδράς όταν θυμώνεις?");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setText("9.Πόσο επηρεάζεσαι από τη γνώμη της παρέας ?");

        buttonGroup7.add(Q71);
        Q71.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Q71.setText("Α. Θυμώνω");

        buttonGroup7.add(Q72);
        Q72.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Q72.setText("<html> Β. Με ενοχλεί, <br> αλλά το ξεπερνάω. </html>");

        buttonGroup7.add(Q73);
        Q73.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Q73.setText("Γ. Την αντιμετωπίζω ήρεμα");

        buttonGroup7.add(Q74);
        Q74.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Q74.setText("<html> Δ. Έχω εκρήξεις θυμού / <br>  Βίαιη συμπεριφορά </html>");

        buttonGroup6.add(Q61);
        Q61.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Q61.setText("<html> Α. Δεν μπορώ να διαχειριστώ <br> το άγχος μου </html>");

        buttonGroup6.add(Q62);
        Q62.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Q62.setText("<html> Β. Συζητώ με άλλους\n<br> το θέμα που με απασχολεί </html>");

        buttonGroup6.add(Q63);
        Q63.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Q63.setText("<html> Γ. Φωνάζω,θυμώνω,\n<br> καταστρέφω πράγματα </html>");

        buttonGroup6.add(Q64);
        Q64.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Q64.setText("<html> Δ. Έχω βρεί τρόπο <br> να μένω ήρεμος/η </html>");

        buttonGroup9.add(Q91);
        Q91.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Q91.setText("Α. Ελάχιστα");

        buttonGroup9.add(Q92);
        Q92.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Q92.setText("Β. Σε φυσιολογικά πλαίσια");

        buttonGroup9.add(Q93);
        Q93.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Q93.setText("Γ. Αρκετά");

        buttonGroup9.add(Q94);
        Q94.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Q94.setText("Δ. Πάρα πολύ");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setText("10.Πως θα αντιδρούσες αν κάποιος/α συμμαθητής/τρια σου έπεφτε θύμα εκφοβισμού?");

        buttonGroup10.add(Q101);
        Q101.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Q101.setText("Α. Δεν θα έκανα τίποτα");

        buttonGroup10.add(Q103);
        Q103.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Q103.setText("Γ. Θα συμμετείχα με τους θύτες");

        buttonGroup10.add(Q102);
        Q102.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Q102.setText("<html> Β. Θα ενημέρωνα κάποιον <br> μεγαλύτερο (γονέα,καθηγητή) </html>");

        buttonGroup10.add(Q104);
        Q104.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Q104.setText("Δ. Θα υπερασπιζόμουν το θύμα");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Πατήστε εδώ για αποστολή απαντήσεων: ");

        calc_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tick.png"))); // NOI18N
        calc_button.setToolTipText("Αποστολή απαντήσεων");
        calc_button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        calc_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc_buttonActionPerformed(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ElhDhmokratia.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2)
                        .addGap(56, 56, 56)
                        .addComponent(labelStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(Q33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(Q31))
                                                    .addGap(32, 32, 32)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(Q32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(113, 113, 113)
                                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(Q61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(Q63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addComponent(Q34))
                                                    .addGap(30, 30, 30)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(Q62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(Q64, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(Q23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(Q21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addGap(39, 39, 39)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(Q24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(103, 103, 103)
                                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(Q53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(Q51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                        .addComponent(Q22))
                                                    .addGap(47, 47, 47)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(Q54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(Q52, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGap(68, 68, 68))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(calc_button, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(21, 21, 21)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(Q91, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Q93, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Q92)
                                                .addComponent(Q94, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(9, 9, 9))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel12)
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(Q81)
                                                    .addGap(27, 27, 27)
                                                    .addComponent(Q82, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addComponent(jLabel15))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(Q83, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Q84, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Q11)
                                        .addComponent(Q13))
                                    .addGap(47, 47, 47)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Q12)
                                        .addComponent(Q14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(89, 89, 89)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Q43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Q41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(47, 47, 47)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Q42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Q44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Q71)
                                        .addComponent(Q73))
                                    .addGap(36, 36, 36)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Q74, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Q72, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14)
                            .addGap(310, 310, 310))))
                .addGap(48, 48, 48))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Q103, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Q101, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Q102, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Q104)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(122, 122, 122)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(labelStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q11)
                    .addComponent(Q12)
                    .addComponent(Q41)
                    .addComponent(Q42)
                    .addComponent(Q71)
                    .addComponent(Q72, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Q13)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Q14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Q43)
                        .addComponent(Q44)
                        .addComponent(Q73)
                        .addComponent(Q74, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Q21)
                            .addComponent(Q22)
                            .addComponent(Q51)
                            .addComponent(Q52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Q82, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Q81, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Q23)
                            .addComponent(Q24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Q53)
                            .addComponent(Q54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Q84, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Q83)))
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q31)
                    .addComponent(Q32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q91)
                    .addComponent(Q92)
                    .addComponent(Q61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q93, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q94, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q34))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Q102, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Q101))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Q103)
                            .addComponent(Q104)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calc_button)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calc_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc_buttonActionPerformed
        int score = 0;
        
        if(Q11.isSelected()){
            score += 10;
        }
        else if(Q12.isSelected()){
            score += 0 ;
        }
        else if(Q13.isSelected()){
            score += 5;
        }
        else if(Q14.isSelected()){
            score += 3 ;
        }
        
        if(Q21.isSelected()){
            score += 3;
        }
        else if(Q22.isSelected()){
            score += 5;
        }
        else if(Q23.isSelected()){
            score += 10;
        }
        else if(Q24.isSelected()){
            score += 0 ;
        }
        
        if(Q31.isSelected()){
            score += 0;
        }
        else if(Q32.isSelected()){
            score += 10 ;
        }
        else if(Q23.isSelected()){
            score += 5;
        }
        else if(Q24.isSelected()){
            score += 3 ;
        }
        
        if(Q41.isSelected()){
            score += 3;
        }
        else if(Q42.isSelected()){
            score += 10 ;
        }
        else if(Q43.isSelected()){
            score += 0;
        }
        else if(Q44.isSelected()){
            score += 5 ;
        }
        
        if(Q51.isSelected()){
            score += 5;
        }
        else if(Q52.isSelected()){
            score += 3;
        }
        else if(Q53.isSelected()){
            score += 10;
        }
        else if(Q54.isSelected()){
            score += 0 ;
        }
        
        if(Q61.isSelected()){
            score += 3;
        }
        else if(Q62.isSelected()){
            score += 5 ;
        }
        else if(Q63.isSelected()){
            score += 0;
        }
        else if(Q64.isSelected()){
            score += 10 ;
        }
        
        if(Q71.isSelected()){
            score += 3;
        }
        else if(Q72.isSelected()){
            score += 5 ;
        }
        else if(Q73.isSelected()){
            score += 10;
        }
        else if(Q74.isSelected()){
            score += 0 ;
        }
        
        if(Q81.isSelected()){
            score += 10;
        }
        else if(Q82.isSelected()){
            score += 3 ;
        }
        else if(Q83.isSelected()){
            score += 0;
        }
        else if(Q84.isSelected()){
            score += 5 ;
        }
        
        if(Q91.isSelected()){
            score += 5;
        }
        else if(Q92.isSelected()){
            score += 10 ;
        }
        else if(Q93.isSelected()){
            score += 3;
        }
        else if(Q94.isSelected()){
            score += 0 ;
        }
        
        
        if(Q101.isSelected()){
            score += 3;
        }
        else if(Q102.isSelected()){
            score += 10 ;
        }
        else if(Q103.isSelected()){
            score += 0;
        }
        else if(Q104.isSelected()){
            score += 5 ;
        }
        
        
        String s = " " + score;
        
        
       if(buttonGroup1.getSelection()==null || buttonGroup2.getSelection()==null || buttonGroup3.getSelection()==null ||
               buttonGroup4.getSelection()==null || buttonGroup5.getSelection()==null || buttonGroup6.getSelection()==null ||
               buttonGroup7.getSelection()==null || buttonGroup8.getSelection()==null || 
               buttonGroup9.getSelection()==null || buttonGroup10.getSelection()==null){
           
           JOptionPane.showMessageDialog(rootPane, "Παρακαλώ για να αποστείλετε τις απαντήσεις διαλέξτε μια απάντηση για κάθε ερώτηση!");
        }   
       else  {
           
           //sql
           
            try{
                String SaveScoreToDB = "UPDATE B2 SET TestScore = ? WHERE StudentID = ?" ;
                pst = dbConnection.prepareStatement(SaveScoreToDB);
                pst.setInt(1, score);
                pst.setString(2, labelStudentId.getText());
                rs = pst.executeQuery();
                rs.close();
                pst.close();
                dbConnection.close(); 
                System.out.println("Τα δεδομένα αποθηκεύτηκαν επιτυχώς!");
            }
           catch(SQLException ex){
                // αν βγαζει εξαιρεση θα ειναι επειδη χρησιμοποιησαμε executeQuery αντι για executeUpdate 
                // με το PreparedStatement
           }
           
           
           JOptionPane.showMessageDialog(rootPane, "Το score αποθηκεύτηκε επιτυχώς!" + ""
                   + " \n \t \t \t \t \t \t \t \t \t \t \t \t \t \t \t \t \t Score: " + score + " / 100");
           System.out.println(" Το score αποθηκεύτηκε επιτυχώς! " + score + " / 100");
           
           
            
           //gia na kleisei to jframe tou quiz
           close();
           Goodbye obj = new Goodbye();
           obj.setVisible(true);
           
       } 
    }//GEN-LAST:event_calc_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PsychologyQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PsychologyQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PsychologyQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PsychologyQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new PsychologyQuiz().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(PsychologyQuiz.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Q101;
    private javax.swing.JRadioButton Q102;
    private javax.swing.JRadioButton Q103;
    private javax.swing.JRadioButton Q104;
    private javax.swing.JRadioButton Q11;
    private javax.swing.JRadioButton Q12;
    private javax.swing.JRadioButton Q13;
    private javax.swing.JRadioButton Q14;
    private javax.swing.JRadioButton Q21;
    private javax.swing.JRadioButton Q22;
    private javax.swing.JRadioButton Q23;
    private javax.swing.JRadioButton Q24;
    private javax.swing.JRadioButton Q31;
    private javax.swing.JRadioButton Q32;
    private javax.swing.JRadioButton Q33;
    private javax.swing.JRadioButton Q34;
    private javax.swing.JRadioButton Q41;
    private javax.swing.JRadioButton Q42;
    private javax.swing.JRadioButton Q43;
    private javax.swing.JRadioButton Q44;
    private javax.swing.JRadioButton Q51;
    private javax.swing.JRadioButton Q52;
    private javax.swing.JRadioButton Q53;
    private javax.swing.JRadioButton Q54;
    private javax.swing.JRadioButton Q61;
    private javax.swing.JRadioButton Q62;
    private javax.swing.JRadioButton Q63;
    private javax.swing.JRadioButton Q64;
    private javax.swing.JRadioButton Q71;
    private javax.swing.JRadioButton Q72;
    private javax.swing.JRadioButton Q73;
    private javax.swing.JRadioButton Q74;
    private javax.swing.JRadioButton Q81;
    private javax.swing.JRadioButton Q82;
    private javax.swing.JRadioButton Q83;
    private javax.swing.JRadioButton Q84;
    private javax.swing.JRadioButton Q91;
    private javax.swing.JRadioButton Q92;
    private javax.swing.JRadioButton Q93;
    private javax.swing.JRadioButton Q94;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JButton calc_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelStudentId;
    // End of variables declaration//GEN-END:variables
}
